/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ResponseRefreshResponse

class ResponseRefreshResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResponseRefreshResponse
        //val modelInstance = ResponseRefreshResponse()

        // to test the property `accessToken`
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `expiresIn`
        should("test expiresIn") {
            // uncomment below to test the property
            //modelInstance.expiresIn shouldBe ("TODO")
        }

    }
}
