/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DiscoverApi
import org.openapitools.client.models.ResponseDiscoverResponse

class DiscoverApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DiscoverApi
        //val apiInstance = DiscoverApi()

        // to test discoverFollowsGet
        should("test discoverFollowsGet") {
            // uncomment below to test discoverFollowsGet
            //val lastId : kotlin.String = lastId_example // kotlin.String | 投稿をフィルタするID
            //val result : ResponseDiscoverResponse = apiInstance.discoverFollowsGet(lastId)
            //result shouldBe ("TODO")
        }

        // to test discoverLatestGet
        should("test discoverLatestGet") {
            // uncomment below to test discoverLatestGet
            //val lastId : kotlin.String = lastId_example // kotlin.String | 投稿をフィルタするID
            //val result : ResponseDiscoverResponse = apiInstance.discoverLatestGet(lastId)
            //result shouldBe ("TODO")
        }

    }
}
