/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.FileApi
import org.openapitools.client.models.ResponseAudioUploadResponse
import org.openapitools.client.models.ResponsePlaylistCreateResponse

class FileApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FileApi
        //val apiInstance = FileApi()

        // to test usersUserIdAudiosPost
        should("test usersUserIdAudiosPost") {
            // uncomment below to test usersUserIdAudiosPost
            //val userId : kotlin.String = userId_example // kotlin.String | ユーザーID
            //val audio : java.io.File = BINARY_DATA_HERE // java.io.File | 音声ファイル
            //val color : kotlin.String = color_example // kotlin.String | イメージカラー
            //val tags : kotlin.String = tags_example // kotlin.String | タグ
            //val result : ResponseAudioUploadResponse = apiInstance.usersUserIdAudiosPost(userId, audio, color, tags)
            //result shouldBe ("TODO")
        }

        // to test usersUserIdPlaylistsPost
        should("test usersUserIdPlaylistsPost") {
            // uncomment below to test usersUserIdPlaylistsPost
            //val userId : kotlin.String = userId_example // kotlin.String | ユーザーID
            //val image : java.io.File = BINARY_DATA_HERE // java.io.File | 画像ファイル
            //val title : kotlin.String = title_example // kotlin.String | プレイリストタイトル
            //val `public` : kotlin.String = `public`_example // kotlin.String | 公開設定(true,false)
            //val result : ResponsePlaylistCreateResponse = apiInstance.usersUserIdPlaylistsPost(userId, image, title, `public`)
            //result shouldBe ("TODO")
        }

    }
}
