/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.TokenApi
import org.openapitools.client.models.ResponseRefreshResponse

class TokenApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TokenApi
        //val apiInstance = TokenApi()

        // to test refreshPost
        should("test refreshPost") {
            // uncomment below to test refreshPost
            //val xRefreshToken : kotlin.String = xRefreshToken_example // kotlin.String | リフレッシュトークン
            //val result : ResponseRefreshResponse = apiInstance.refreshPost(xRefreshToken)
            //result shouldBe ("TODO")
        }

    }
}
