/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.UserApi
import org.openapitools.client.models.RequestUserSigninRequest
import org.openapitools.client.models.RequestUserSignupRequest
import org.openapitools.client.models.ResponseUserInfoResponse
import org.openapitools.client.models.ResponseUserSigninResponse
import org.openapitools.client.models.ResponseUserSignupResponse

class UserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserApi
        //val apiInstance = UserApi()

        // to test signinPost
        should("test signinPost") {
            // uncomment below to test signinPost
            //val request : RequestUserSigninRequest =  // RequestUserSigninRequest | ユーザーログインリクエスト
            //val result : ResponseUserSigninResponse = apiInstance.signinPost(request)
            //result shouldBe ("TODO")
        }

        // to test signupPost
        should("test signupPost") {
            // uncomment below to test signupPost
            //val request : RequestUserSignupRequest =  // RequestUserSignupRequest | ユーザーログインリクエスト
            //val result : ResponseUserSignupResponse = apiInstance.signupPost(request)
            //result shouldBe ("TODO")
        }

        // to test usersMeGet
        should("test usersMeGet") {
            // uncomment below to test usersMeGet
            //val result : ResponseUserInfoResponse = apiInstance.usersMeGet()
            //result shouldBe ("TODO")
        }

    }
}
