/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param email 
 * @param id 
 * @param name 
 * @param updatedAt 
 */


data class ResponseUserInfoResponse (

    @Json(name = "createdAt")
    val createdAt: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "updatedAt")
    val updatedAt: kotlin.String

) {


}

