/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param color 
 * @param createdAt 
 * @param fileName 
 * @param id 
 * @param tags 
 * @param updatedAt 
 * @param userId 
 */


data class ResponseDiscoverResponseItem (

    @Json(name = "color")
    val color: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: kotlin.String,

    @Json(name = "fileName")
    val fileName: kotlin.String,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @Json(name = "updatedAt")
    val updatedAt: kotlin.String,

    @Json(name = "userId")
    val userId: kotlin.String

) {


}

